### ISSUE TITLE
Memory corruption error  `euclidean_matrix`

### ISSUE THREAD

**Issue by dekuenstle** [ViCCo-Group/THINGSvision#4]
Hey,

when I call `euclidean_matrix` (through `compute_rdm(x, 'euclidean')`), the execution crashes with `double free or corruption (!prev)` (input: features from alexnet layers). Unfortunately, no more error logs are created. The other distance metrics work fine. 
We run python 3.8 with CUDA 10.2 in a container. The python packages are up-to-date. 

Can you reproduce that the `euclidean_matrix` does not work, or is it specific to our setup?

Thanks
David

EDIT: If anyone else has the same problem, I use scipy's `squareform` + `pdist` functions as a workaround. I did not benchmark, but it seems pretty fast.

**Comment by LukasMut** [comment]
Hi David,

I've just looked into this issue and figured out that the problem is Numba (`euclidean_matrix` uses Numba to leverage parallelization for faster computations), which does not seem to work well with CUDA or in a container. I've just modified the function to get it to work. Please upgrade `thingsvision` to the most recent version and let me know whether everything works as expected.

Cheers
L

**Comment by dekuenstle** [comment]
Thanks for the speedy response & fix, Lukas!
