### ISSUE TITLE
Return copy of activations

### ISSUE THREAD

**Issue by hannamw** [ViCCo-Group/THINGSvision#44]
I think there's a rather serious (but fortunately easily fixable!) problem with THINGSvision. Namely, in the hook that retrieves model activations, the dictionary `activations` is given a pointer to the original tensor `output` rather than a copy of `output`. This means that a layer that operates in-place, such as `ReLU(inplace=True)`, can modify our activation tensor, even if said layer comes after the layer whose activations we are extracting. 

To replicate this, you can use the pytorch Colab notebook given, and extract features for Alexnet on pretty much any image. Examining the features from layer `features.0` (a 2D convolution), all entries are non-negative, and many are 0. This is because the following layer, `features.1`, is an in-place ReLU operation, and overwrote all of the negative entries.

To solve this, the dictionary `activations` should store a copy of the tensor, rather than the original tensor. I'm happy to make a PR and fix this myself, but I thought I would also bring it to folks' attention here as well.

**Comment by LukasMut** [comment]
Hi Michael! Thanks a lot for pointing this out! We always appreciate feedback, especially of this useful sort. I've just fixed that issue. The `activations` dictionary now points to a copy of `output` rather than to `output` itself. Could you confirm that the behavior you've experienced is now resolved, and all entries of `features.0` are not just non-negative reals?

**Comment by hannamw** [comment]
Hi Lukas - yes, it looks like the negative activations are preserved now. Thanks for the quick fix!
