### ISSUE TITLE
README improvement

### ISSUE THREAD

**Issue by LukasMut** [ViCCo-Group/thingsvision#66]
Improve readability of README file. Make text more concise and easier understandable?

**Comment by PhilippKaniuth** [comment]
- Include warning at the beginning that some original function calls mentioned in the paper are deprecated and that users should follow exclusively follow the README.

**Comment by andropar** [comment]
- Example snippets repeat alot of code, I think a general overview about what models are available and one example for how to call the extractor should be sufficient

**Comment by oliver-contier** [comment]
The readme very intuitive! I have a few suggestions, but none of them are critical imo. 

- In "About the project": Consider changing "bunch of images" to "a directory of images" or similar
- In "Functionality": "extract features for the THINGS image database" is implicitly true from the previous two bullet points. I guess you aim to say something like "Conveniently access features for >26,000 images in the THINGS image database" to emphasize convenience?
- "use HDF5 datasets": Sounds like a technical detail, maybe it's sufficient to mention this in the docs? The rest of the readme seems to be more of a high-level overview.
- Under "Basic usage" -> "module_name": Maybe you could mention - in a short sentence - what you mean by "module"? Laymen might not be familiar?
- In the example call for AlexNet: Is it possible to make it more visually distinct, which parts are code and which parts are console output? Otherwise, users might think they have to manually specify that big chunk of output produced by `extractor.show_model()`
- Acknowledgements: I assume this section is not finalized yet? :)

**Comment by LukasMut** [comment]
@oliver-contier could you add your review and make these changes (except for the final two points) in the PR?
